# 备选：HTTP 换另一个 CDN 节点
listen_port=65080;
worker_proc=0;
daemon=on;
uid=3004;
mode=net;

http_ip=106.225.194.35;
http_port=80;
http_del="X-Online-Host";
http_first="[M]http://chinaunicom-playe-free.10010.com/videoworks/mda-mfqg4w0xr7mr536n/unicom_work_pro/transcode/162373672496113.mp4 [V]\r\n";

https_connect=on;
https_ip=14.215.182.75;
https_port=443;
https_del="User-Agent";
https_first="[M][H]@pull.free.video.10010.com [V]\r\n";

dns_tcp=http;
dns_listen_port=65053;
dns_url="119.29.29.29";
